-- AlterTable
ALTER TABLE "User" ADD COLUMN     "photo" TEXT,
ADD COLUMN     "showOnAbout" BOOLEAN NOT NULL DEFAULT true,
ALTER COLUMN "role" DROP DEFAULT,
ALTER COLUMN "position" DROP NOT NULL,
ALTER COLUMN "position" DROP DEFAULT;
